### PR TITLE
use specific imports for lodash

### PR DESCRIPTION
**Pull request by alinaMihai**
Sorry about changing the formatting, I had prettier on save.

### CODE REVIEW

**Comment by azizali** [comment]
@alinaMihai my built was 
 main.js  20.2 kB 
Yours is:
 main.js  21.2 kB  

I am looking in the /dist folder when I do `npm run build`

where are you seeing this?

**Comment by alinaMihai** [comment]
hi @azizali , I've also noticed an increase in main.js, maybe because there are multiple lines for the imports, I don't know. But, the added value comes from not importing the whole Lodash library anymore.
 
Even though the main.js distribution is small in size, because it requires the whole lodash library, it ends up in the final bundle, as it is mentioned in the bundlephobia (https://bundlephobia.com/result?p=react-super-treeview@0.3.2 ): 
"These sizes represent the contribution made by dependencies (direct or transitive) to react-super-treeview's size. These may be different from the dependencies' standalone sizes."

image

The difference for me is visible in my application where I use thie react-super-treeview, as the vendors bundle is smaller.

**Comment by azizali** [comment]
Is there a way for me to see the bundlephobia Results before publishing the
module?

Also did you see that the bundlephobia was working better with your changes?

**Comment by azizali** [comment]
@alinaMihai I just published version 0.3.3 with the lodash change, hoping to see bundlephobia shows the stats but its not. Maybe bundlephobia is cached or whatever.

Let's see when bundlephobia updates its data and what it says:
https://bundlephobia.com/result?p=react-super-treeview@0.3.3

**Comment by alinaMihai** [comment]
hi @azizali, the way I actually tested this was by changing the distribution of react-super-treeview in my project with the new one and analyze the bundle size of my vendors bundle, and it decreased.

I see this when opening bundlephobia :
PackageVersionMismatchError
This package has not been published with this particular version. Valid versions - `latest`, `0.0.1`, `0.0.2`, `0.0.3`, `0.1.0`, `0.2.0`, `0.2.1`, `0.3.0`, `0.3.1` and `0.3.2`

**Comment by azizali** [comment]
Yup, I see the same. I believe bundlephobia is caching it's outputs.

I just published version 0.3.3 with the lodash-es optimization.

Can you share the before and after in your more package?

0.3.2 vs. 0.3.3

It's not a real test but still

**Comment by alinaMihai** [comment]
Hi,
try https://bundlephobia.com/result?p=react-super-treeview@0.3.3-beta.0 

image

**Comment by azizali** [comment]
screen shot 2019-02-09 at 12 38 07 pm

Yeah it worked

Thanks or the tip, I think there should be another way to test these things, I was just looking at my own package.

**Pull request closed without merging**
